version: '3.7'

services:
  logistic_regression_api_db:
    image: postgres:alpine
    container_name: logistic_regression_api_db
    network_mode: host
    volumes:
      - logistic_regression_api_db_data:/var/lib/postgresql/data/
    env_file:
      - .env
  logistic_regression_api_pgadmin:
    image: dpage/pgadmin4
    container_name: logistic_regression_api_pgadmin
    network_mode: host
    depends_on:
      - logistic_regression_api_db
    env_file:
      - .env
  
volumes:
  logistic_regression_api_db_data:
