# Generated by Django 3.2.10 on 2022-05-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifiers", "0002_classifier_datafile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datafile",
            name="file_path",
            field=models.FileField(upload_to="files/data-files"),
        ),
    ]
