# Generated by Django 3.2.10 on 2022-05-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classifiers", "0003_alter_datafile_file_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFileHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "data_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classifiers.datafile",
                    ),
                ),
            ],
        ),
    ]
