# Generated by Django 3.2.10 on 2022-05-26 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classifiers", "0009_rename_predictor_predictioninputdata_prediction"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="datafile",
            table="data_file",
        ),
        migrations.AlterModelTable(
            name="datafileheader",
            table="data_file_header",
        ),
        migrations.AlterModelTable(
            name="predictioninputdata",
            table="prediction_input_data",
        ),
    ]
