# Generated by Django 3.2.10 on 2022-05-26 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classifiers", "0011_auto_20220526_0223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictioninputdata",
            name="input_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classifiers.datafileheader",
            ),
        ),
    ]
