# Generated by Django 3.2.10 on 2022-05-26 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classifiers", "0012_alter_predictioninputdata_input_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictioninputdata",
            name="data_file_header",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classifiers.datafileheader",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="predictioninputdata",
            name="input_label",
            field=models.CharField(max_length=255),
        ),
    ]
